name: Pip.Services Commons toolkit in .NET

on: 
  push:
    paths:
    - '**'
    - '!README.md'

jobs:
  Default:
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@main
  
    ############# Prepare #############

    - name: Save build number and component version
      id: build_info
      run: |
        echo "##[set-output name=build_number;]$GITHUB_RUN_NUMBER"
        echo "##[set-output name=component_version;]$(jq -r '.version' ./component.json)"
        echo "##[set-output name=component_name;]$(jq -r '.name' ./component.json)"

    - name: Install powershell
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https
        wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell

    ############# Build and test #############

    - name: Build the component
      run: ./build.ps1

    - name: Test the component
      run: ./test.ps1

    ############# Release #############

    - name: Tag branch with the build number
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: "v${{ steps.build_info.outputs.component_version }}-${{ steps.build_info.outputs.build_number }}"

    - name: Release binary artifacts
      run: ./release.ps1
      env: 
        NUGET_KEY: ${{ secrets.NUGET_KEY }}

    ############# Clear #############

    - name: Clean temporary build artifacts
      if: ${{ always() }}
      run: ./clean.ps1
    